name: .NET CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test

    - name: Publish Application
      run: dotnet publish -c Release -o publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: publish

    - name: Deploy to IIS Server
      run: |
       Copy-Item -Path publish\* -Destination \\SERVER-IP\C$\inetpub\Finance_App -Recurse -Force
